version: '3.9'

services:
  #База даних
  db:
    image: postgres:15 #готовий офіційний образ
    environment:
      POSTGRES_DB: hotel_db #ім'я бази
      POSTGRES_USER: hotel_user #користувач БД
      POSTGRES_PASSWORD: hotel_pass  #пароль
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
  #Веб частина застосунку
    build: . #збирає образ з Dockerfile у поточній директорії
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://hotel_user:hotel_pass@db:5432/hotel_db
      DEBUG: "True"
      SECRET_KEY: "django-insecure-docker-dev-key"

volumes:
  postgres_data: